### ISSUE TITLE
toolset gcc initalization error

### ISSUE THREAD

**Issue by jazzzheng** [ATNoG/odtone-openwrt#2]
Hello, cguimaraes :

I had to try to build the odtone-0.6 on openwrt，but the errors occuried : 

"( cd /home/wmnlab/openwrt_1407/openwrt/build_dir/target-mips_34kc_uClibc-0.9.33.2/ODTONE-0.6 ; AR=mips-openwrt-linux-ar LD=mips-openwrt-linux-ld NM=mips-openwrt-linux-nm CC=mips-openwrt-linux-gcc GCC=mips-openwrt-linux-gcc CXX=mips-openwrt-linux-g++ RANLIB=mips-openwrt-linux-ranlib STRIP=mips-openwrt-linux-strip OBJCOPY=mips-openwrt-linux-objcopy OBJDUMP=mips-openwrt-linux-objdump b2 src/mihf app/sap_80211_linux app/sap_8023 app/link_sap_icmp -j1 toolset=gcc-mips --build-type=minimal --layout=system optimization=space --disable-long-double link=shared runtime-link=shared inlining=on debug-symbols=off --target=mips-openwrt-linux --host=mips-openwrt-linux --build=x86_64-linux-gnu --program-prefix="" --program-suffix="" --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --libexecdir=/usr/lib --sysconfdir=/etc --datadir=/usr/share --localstatedir=/var --mandir=/usr/man --infodir=/usr/info --disable-nls   linkflags="-lpthread -lgcc_eh -lboost_program_options -lboost_system -lboost_thread -lnl-3 -lnl-genl-3 -lnl-route-3" include=/home/wmnlab/openwrt_1407/openwrt/staging_dir/target-mips_34kc_uClibc-0.9.33.2/usr/include/libnl3 release )
/usr/local/share/boost-build/src/tools/gcc.jam:122: in gcc.init from module gcc
error: toolset gcc initialization:
error: version 'mips' requested but 'g++-mips' not found and version '4.8' of default 'g++' does not match
error: initialized from
/usr/local/share/boost-build/src/build/toolset.jam:43: in toolset.using from module toolset
/usr/local/share/boost-build/src/build-system.jam:461: in process-explicit-toolset-requests from module build-system
/usr/local/share/boost-build/src/build-system.jam:527: in load from module build-system
/usr/local/share/boost-build/src/kernel/modules.jam:295: in import from module modules
/usr/local/share/boost-build/src/kernel/bootstrap.jam:139: in boost-build from module
/usr/local/share/boost-build/boost-build.jam:8: in module scope from module

make[2]: **\* [/home/wmnlab/openwrt_1407/openwrt/build_dir/target-mips_34kc_uClibc-0.9.33.2/ODTONE-0.6/.built] Error 1
make[2]: Leaving directory `/home/wmnlab/openwrt_1407/odtone-openwrt/odtone-0.6'
make[1]: *** [package/odtone-0.6/compile] Error 2
make[1]: Leaving directory`/home/wmnlab/openwrt_1407/openwrt'
make: **\* [package/odtone-0.6/compile] Error 2"

How can I do to solve this problem?
Thank you.

Evans Zheng
Best Regards

**Comment by cguimaraes** [comment]
Have you defined gcc-mips in user-config.jam?
If not, you can do it with the following command (you need to replace `<PATH_TO_OPENWRT_FOLDER>` and `<TOOLCHAIN_FOLDER>`):

```
echo "using gcc : mips : <PATH_TO_OPENWRT_FOLDER>/staging_dir/<TOOLCHAIN_FOLDER>/bin/<PREFIX>-g++ ;" > ~/user-config.jam
```

You may also need to define the following environment variables (you need to replace `<PATH_TO_OPENWRT_FOLDER>` and `<TOOLCHAIN_FOLDER>`):

```
export STAGING_DIR=<PATH_TO_OPENWRT_FOLDER>/staging_dir/<TOOLCHAIN_FOLDER>
export PATH=$PATH:<PATH_TO_OPENWRT_FOLDER>/staging_dir/<TOOLCHAIN_FOLDER>/bin/
```

**Comment by jazzzheng** [comment]
Hello, cguimaraes :

Thank you for your reply, this problem has been successfully resolved!!
Thank you so much!

Evans Zheng
Best Regards

**Comment by jazzzheng** [comment]
Hello, cguimaraes :

Sorry, I would like to ask a question:
Can I trigger the MIES from SAP to start the proccess of mobile handover?

Evans Zheng
Best Regards
